geekshop/basket/urls.py
from django.urls import re_path
from .views import (MainView, ContView, ProdView, ProdCategoryView,
                    ProdDetailView, AddProductView, DelProductView, UpdateProductView, OrderProductView, BasketView,
                    createPictureView, pictureView, deletePictureView, OrderDeleteProductView, OrderAddProductView,
                    PayInvoiceView, basket_edit, DeleteProductFromOrder)


app_name = 'basket'

urlpatterns = [
    re_path(r'index/', MainView.as_view(), name='mainView'),
    re_path(r'^$', MainView.as_view(), name='mainView'),
    re_path(r'products/page/(?P<page>\d+)/', ProdView.as_view(), name='prodView'),
    re_path(r'contact/', ContView.as_view(), name='contView'),
    re_path(r'products/category/(?P<cat_id>\d+)/page/(?P<page>\d+)/', ProdCategoryView.as_view(), name='prodCategoryView'),
    re_path(r'products/(?P<slug>\d+)/', ProdDetailView.as_view(), name='prodDetailView'),
    re_path(r'^addproduct/(?P<cat_id>\d+)', AddProductView.as_view(), name='addProductView'),
    re_path(r'^delproduct/(?P<pk>\d+)/', DelProductView.as_view(), name='delProductView'),
    re_path(r'edit_basket/(?P<pk>\d+)/(?P<quantity>\d+)/$', basket_edit, name='basket_edit'),
    re_path(r'delete_product_basket/(?P<pk>\d+)/$', DeleteProductFromOrder.as_view(), name='deleteProductFromOrder'),
    re_path(r'updateproduct/(?P<pk>\d+)/', UpdateProductView.as_view(), name='updateProductView'),
    re_path(r'order/(?P<pk>\d+)', OrderProductView.as_view(), name='orderProductView'),
    re_path(r'order/deleteproduct/(?P<pk>\d+)/', OrderDeleteProductView.as_view(), name='orderDeleteProductView'),
    re_path(r'order/addproduct/(?P<pk>\d+)/', OrderAddProductView.as_view(), name='orderAddProductView'),
    re_path(r'^basket/', BasketView.as_view(), name='basketView'),
    re_path(r'createPicture/(?P<related_obj>\d+)/', createPictureView.as_view(), name='createPicture'),
    re_path(r'picture/(?P<pk>\d+)/', pictureView.as_view(), name='pictureView'),
    re_path(r'deletePicture/(?P<pk>\d+)/', deletePictureView.as_view(), name='deletePicture'),
    re_path(r'payinvoice/', PayInvoiceView.as_view(), name='payinvoice')
]

geekshop/geekshop/urls.py
import os
from django.contrib import admin
from django.urls import include, re_path
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import login, MyPasswordResetDoneView, MyPasswordResetConfirmView, MyPasswordResetCompleteView
import basket.views as basket

app_name = 'geekshop'

urlpatterns = [
    re_path(r'^$', basket.MainView.as_view(), name='main'),
    re_path(r'', include('basket.urls', namespace='basket')),
    re_path(r'admin/', admin.site.urls),
    re_path(r'admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r'^ordersapp/', include('ordersapp.urls', namespace='order')),
    re_path(r'^auth/verify/google/oauth2/', include("social_django.urls", namespace="social")),
    re_path(r'auth/', include('accounts.urls', namespace='accounts')),
    re_path(r'^rosetta/', include('rosetta.urls')),
    re_path(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^accounts/password/reset/done/$', MyPasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^reset/confirm/done/$', MyPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    re_path(r'accounts/login/', login.as_view(), name='login'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#if settings.DEBUG:
#    import debug_toolbar
#    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path

app_name = "ordersapp"

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),

    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),

    re_path(r'^product/(?P<pk>\d+)/price/$', ordersapp.get_product_price),
]

geekshop/ordersapp/models.py
from django.db import models

from django.conf import settings
from basket.models import Product


class MegaOrder(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(verbose_name='статус', max_length=3, choices=ORDER_STATUS_CHOICES, default=FORMING)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return 'Текущий заказ: {}'.format(self.id)

    def get_summary(self):
        items = self.orderitems.select_related()
        result = {
            'total_quantity': sum(list(map(lambda x: x.quantity, items))),
            'get_total_cost': sum(list(map(lambda x: x.quantity * x.product.prices.all()[0].value, items)))
        }
        return result


    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.prices.all()[0].value, items)))

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(MegaOrder, related_name="orderitems", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='продукт', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    def get_product_cost(self):
        return self.product.prices.all()[0].value * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.filter(pk=pk).first()

geekshop/ordersapp/forms.py
from django import forms

from ordersapp.models import MegaOrder, OrderItem
from basket.models import Product

from django.conf import settings
from django.core.cache import cache


class OrderForm(forms.ModelForm):
    class Meta:
        model = MegaOrder
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        exclude = ()
        # fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        if settings.LOW_CACHE:
            key = 'orderitemform_products'
            products = cache.get(key)
            if products is None:
                products = Product.get_items().prefetch_related()
                cache.set(key, products)
        else:
            products = Product.get_items().prefetch_related()

        self.fields['product'].queryset = products

geekshop/ordersapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, HttpResponseRedirect

from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.views.generic.detail import DetailView
from ordersapp.models import MegaOrder, OrderItem

from django.urls import reverse, reverse_lazy
from django.db import transaction

from ordersapp.forms import OrderItemForm
from django.forms import inlineformset_factory

from basket.models import Invoice, Order, Product

from django.dispatch import receiver
from django.db.models.signals import pre_save, pre_delete

from django.http import JsonResponse

from django.db.models import F
from django.conf import settings

class OrderList(LoginRequiredMixin, ListView):
    model = MegaOrder

    def get_queryset(self):
        return MegaOrder.objects.filter(user=self.request.user)


class OrderItemsCreate(CreateView):
    model = MegaOrder
    fields = []
    success_url = reverse_lazy('ordersapp:orders_list')

    def post(self, request, *args, **kwargs):
        OrderFormSet = inlineformset_factory(MegaOrder, OrderItem, form=OrderItemForm, extra=1)
        formset = OrderFormSet(self.request.POST)
        self.formset = formset
        return super().post(request, *args, **kwargs)
    #
    def get(self, request, *args, **kwargs):

        invoice_qs = Invoice.objects.get_active().filter(users=self.request.user)
        basket_items = []
        if (invoice_qs.exists()):
            basket_items = Order.objects.filter(invoices=invoice_qs[0])

        if len(basket_items):
            OrderFormSet = inlineformset_factory(MegaOrder, OrderItem, form=OrderItemForm, extra=len(basket_items))
            self.formset = OrderFormSet()
            for num, form in enumerate(self.formset.forms):
                form.initial['product'] = basket_items[num].ware
                form.initial['quantity'] = basket_items[num].counts
                form.initial['price'] = basket_items[num].ware.prices.all()[0].value
            # self.basket_items = basket_items
        else:
            OrderFormSet = inlineformset_factory(MegaOrder, OrderItem, form=OrderItemForm, extra=1)
            self.formset = OrderFormSet()
        return super().get(request, *args, **kwargs)


    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['orderitems'] = self.formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

                invoice_qs = Invoice.objects.get_active().filter(users=self.request.user)
                if (invoice_qs.exists()):
                    basket_items = Order.objects.filter(invoices=invoice_qs[0])
                    basket_items.delete()
                    invoice_qs[0].delete()

        # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsCreate, self).form_valid(form)


class OrderRead(DetailView):
    model = MegaOrder

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'заказ/просмотр'
        return context



class OrderItemsUpdate(UpdateView):
    model = MegaOrder
    fields = []
    success_url = reverse_lazy('ordersapp:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsUpdate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(MegaOrder, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            data['orderitems'] = OrderFormSet(self.request.POST, instance=self.object)
        else:
            queryset = self.object.orderitems.select_related()
            formset = OrderFormSet(instance=self.object, queryset=queryset)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.prices.all()[0].value
            data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsUpdate, self).form_valid(form)


class OrderDelete(DeleteView):
    model = MegaOrder
    success_url = reverse_lazy('ordersapp:orders_list')
    # template_name = 'delete_confirm.html'

def order_forming_complete(request, pk):
    if request.method == 'POST':
        order = get_object_or_404(MegaOrder, pk=pk)
        order.status = MegaOrder.SENT_TO_PROCEED
        order.save()
        return HttpResponseRedirect(reverse('ordersapp:orders_list'))
    else:
        raise Http404


def get_product_price(request, pk):
    if request.is_ajax():
        product = Product.objects.filter(pk=int(pk)).first()
        if product:
            return JsonResponse({'price': product.prices.all()[0].value})
        else:
            return JsonResponse({'price': 0})


@receiver(pre_save, sender=OrderItem)
def product_quantity_update_save(sender, update_fields, instance, **kwargs):
    if update_fields is 'quantity' or 'product':
        if instance.pk:
            if str(type(sender.get_item(instance.pk))) != "<class 'NoneType'>":
                instance.product.quantity = F('quantity') - (instance.quantity - sender.get_item(instance.pk).quantity)
        else:
            instance.product.quantity = F('quantity') - instance.quantity
        instance.product.save()


@receiver(pre_delete, sender=OrderItem)
def product_quantity_update_delete(sender, instance, **kwargs):
    instance.product.quantity = F('quantity') + instance.quantity
    instance.product.save()

geekshop/ordersapp/templates/ordersapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'basket/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'basket/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'basket/fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'basket/js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'basket/js/orders_scripts.js' %}"></script>
        <script src="{% static 'basket/js/jquery.formset.js' %}"></script>
    {% endblock %}
</head>
<body>
	<div class="order_container">
        {% block content %}

        {% endblock %}
        
	</div>
</body>
</html>

geekshop/ordersapp/templates/ordersapp/megaorder_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="category_delete">
        <div class="h1">Уверены, что хотите удалить?</div>
        {% include 'ordersapp/includes/inc_order_summary.html' %}
        <form action="{% url 'ordersapp:order_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'ordersapp:orders_list' %}">отмена</a>
        </button>
    </div>
{% endblock %}

geekshop/ordersapp/templates/ordersapp/megaorder_detail.html
{% extends "ordersapp/base.html" %}
{% load static %}

{% block content %}
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <div class="basket_list">
        {% for item in object.orderitems.select_related %}
            <div class="basket_record">
                <img src="{{ item.product.pictures.all.0.image.url }}" alt="{{ item.product.description }}">
                <span class="category_name">{{ item.product.category.title }}</span>
                <span class="product_name">{{ item.product.title }}</span>
                <span class="product_price">{{ item.product.prices.all.0.value }}&nbspруб</span>
                <span class="product_quantitiy">x {{ item.quantity }} шт.</span>
                <span class="product_cost"> = {{ item.get_product_cost }}&nbspруб</span>
            </div>
        {% endfor %}
    </div>
    {% include 'ordersapp/includes/inc_order_actions.html' %}

{% endblock %}

geekshop/ordersapp/templates/ordersapp/megaorder_form.html
{% extends "ordersapp/base.html" %}
{% load static %}
{% load cache %}

{% block content %}
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <div class="order_form">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <table class="table">
                {{ orderitems.management_form }}
                {% for form in orderitems.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                    {{ field.label|capfirst }}
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="formset_row">
                        {% for field in form.visible_fields %}
                            <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {% if field.name != 'price' %}
                                    {% if field.name == 'product5' %}
                                        {% cache 3600 orderitemform_product field.value %}
                                            {{ field }}
                                        {% endcache %}
                                    {% else %}
                                        {{ field }}
                                    {% endif %}
                                {% else %}
                                    {% if field.value %}
                                        <span class="orderitems-{{forloop.parentloop.counter0}}-price">
                                            {{ field.value }}
                                        </span> руб
                                    {% endif %}
                                {% endif %}
                            </td>

                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">сохранить</button>
            {% include 'ordersapp/includes/inc_order_actions.html' %}
        </form>
    </div>

{% endblock %}

geekshop/ordersapp/templates/ordersapp/megaorder_list.html
{% extends 'ordersapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="h2 text-center head">
        Ваши заказы, {% if user.first_name %}{{ user.first_name|title}}{% else %}{{user.username}}{% endif %}
    </div>
    <table class="table orders_list">
        <thead>
          <tr>
            <th>ID</th>
            <th>Создан</th>
            <th>Обновлен</th>
            <th>Статус</th>
          </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
                {% if item.is_active %}
                <tr>
                    <td class="td1 orders_list">{{ item.pk }}</td>
                    <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.get_status_display }}</td>
                    <td>
                        <a href="{% url 'ordersapp:order_read' item.pk %}">посмотреть</a>
                    </td>
                    <td>
                        {% if item.status == item.FORMING %}
                            <a href="{% url 'ordersapp:order_update' item.pk %}">редактировать</a>
                        {% endif %}
                    </td>
                    <td>
                        {% if item.status == item.FORMING %}
                            <a href="{% url 'ordersapp:order_delete' item.pk %}">удалить</a>
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
    <button class="btn btn-default btn-round">
        <a href="{% url 'main' %}">
            на главную
        </a>
    </button>
    <button class="btn btn-default btn-round">
        <a href="{% url 'ordersapp:order_create' %}">
            новый
        </a>
    </button>
{% endblock %}