geekshop/accounts/urls.py
from django.urls import re_path
from .views import (login, logout,
    createProfileView, profileView, changeProfileView, deleteProfileView,
    createAvatarView, avatarView, changeAvatarView, deleteAvatarView, MyPasswordResetView, register, verify, edit)

app_name = 'accounts'

urlpatterns = [
    re_path('login/', login.as_view(), name='login'),
    re_path('logout/', logout.as_view(), name='logout'),
    re_path('profile/', profileView.as_view(), name='profile'),
    re_path('edituserprof/', edit, name='edit'),
    re_path('deleteprofile/',  deleteProfileView.as_view(), name='deleteProfile'),
    re_path('createavatar/',  createAvatarView.as_view(), name='createAvatar'),
    re_path('delavatar/(?P<pk>\d+)/',  deleteAvatarView.as_view(), name='deleteAvatar'),
    re_path(r'password_reset', MyPasswordResetView.as_view(), name='password_reset'),
    re_path(r'^register/$', register, name='register'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w*)/$', verify, name='verify'),
]

geekshop/basket/urls.py
from django.urls import re_path
from .views import (MainView, ContView, ProdView, ProdCategoryView,
                    ProdDetailView, AddProductView, DelProductView, UpdateProductView, OrderProductView, BasketView,
                    createPictureView, pictureView, deletePictureView, OrderDeleteProductView, OrderAddProductView,
                    PayInvoiceView, basket_edit, DeleteProductFromOrder)


app_name = 'basket'

urlpatterns = [
    re_path(r'index/', MainView.as_view(), name='mainView'),
    re_path(r'^$', MainView.as_view(), name='mainView'),
    re_path(r'products/page/(?P<page>\d+)/', ProdView.as_view(), name='prodView'),
    re_path(r'contact/', ContView.as_view(), name='contView'),
    re_path(r'products/category/(?P<cat_id>\d+)/page/(?P<page>\d+)/', ProdCategoryView.as_view(), name='prodCategoryView'),
    re_path(r'products/(?P<slug>\d+)/', ProdDetailView.as_view(), name='prodDetailView'),
    re_path(r'^addproduct/(?P<cat_id>\d+)', AddProductView.as_view(), name='addProductView'),
    re_path(r'^delproduct/(?P<pk>\d+)/', DelProductView.as_view(), name='delProductView'),
    re_path(r'edit_basket/(?P<pk>\d+)/(?P<quantity>\d+)/$', basket_edit, name='basket_edit'),
    re_path(r'delete_product_basket/(?P<pk>\d+)/$', DeleteProductFromOrder.as_view(), name='deleteProductFromOrder'),
    re_path(r'updateproduct/(?P<pk>\d+)/', UpdateProductView.as_view(), name='updateProductView'),
    re_path(r'order/(?P<pk>\d+)', OrderProductView.as_view(), name='orderProductView'),
    re_path(r'order/deleteproduct/(?P<pk>\d+)/', OrderDeleteProductView.as_view(), name='orderDeleteProductView'),
    re_path(r'order/addproduct/(?P<pk>\d+)/', OrderAddProductView.as_view(), name='orderAddProductView'),
    re_path(r'^basket/', BasketView.as_view(), name='basketView'),
    re_path(r'createPicture/(?P<related_obj>\d+)/', createPictureView.as_view(), name='createPicture'),
    re_path(r'picture/(?P<pk>\d+)/', pictureView.as_view(), name='pictureView'),
    re_path(r'deletePicture/(?P<pk>\d+)/', deletePictureView.as_view(), name='deletePicture'),
    re_path(r'payinvoice/', PayInvoiceView.as_view(), name='payinvoice')
]

geekshop/geekshop/urls.py
import os
from django.contrib import admin
from django.urls import include, re_path
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import login, MyPasswordResetDoneView, MyPasswordResetConfirmView, MyPasswordResetCompleteView
import basket.views as basket

app_name = 'geekshop'

urlpatterns = [
    re_path(r'^$', basket.MainView.as_view(), name='main'),
    re_path(r'', include('basket.urls', namespace='basket')),
    re_path(r'admin/', admin.site.urls),
    re_path(r'admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r'^ordersapp/', include('ordersapp.urls', namespace='order')),
    re_path(r'^auth/verify/google/oauth2/', include("social_django.urls", namespace="social")),
    re_path(r'auth/', include('accounts.urls', namespace='accounts')),
    re_path(r'^rosetta/', include('rosetta.urls')),
    re_path(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^accounts/password/reset/done/$', MyPasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^reset/confirm/done/$', MyPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    re_path(r'accounts/login/', login.as_view(), name='login'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#if settings.DEBUG:
#    import debug_toolbar
#    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/basket/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.db.models import Sum, F, FloatField
from django.utils.functional import cached_property

# warenkorb
# Create your models here.

class Core(models.Model):
    """ базовый класс для моделей """
    title = models.CharField(_('dc-title'), max_length=250, default='', blank=True, null=False)
    description = models.TextField(_('dc-description'), null=True, blank=True)
    sort = models.IntegerField(_(u'sort'), default=0, blank=True, null=True)
    active = models.BooleanField(_(u'active'), default=False)

    def __str__(self):
        return '{}'.format(self.title)


class Picture(Core):
    """ модель картинки """
    class Meta:
        verbose_name = _('Картинка')
        verbose_name_plural = _('Картинки')

    image = models.ImageField(upload_to='images')
    related_obj = models.ForeignKey(Core, verbose_name=_(u'pictures'), null=True, blank=True, related_name='pictures', on_delete=models.SET_NULL)

class ProductCategory(Core):
    """ модель категории продукта """
    class Meta:
        verbose_name = _('Продуктовая категория')
        verbose_name_plural = _('Продуктовые категории')
        ordering = ('sort',)

class Contact(models.Model):
    """ модель контакта """
    class Meta:
        verbose_name = _('Контакт')
        verbose_name_plural = _('Контакты')

    telephone = models.CharField(_('telephone'), max_length=30, default='-', blank=True, null=False)
    email = models.CharField(_('email'), max_length=100, default='', blank=True, null=False)
    address = models.CharField(_('address'), max_length=250, default='', blank=True, null=False)


class Producer(Core):
    """ модель производителя """
    class Meta:
        verbose_name = _('Производитель')
        verbose_name_plural = _('Производители')
        ordering = ('sort',)

    contacts = models.ForeignKey(Contact, null=True, on_delete=models.SET_NULL)

class Product(Core):
    """ модель продукта """
    class Meta:
        verbose_name = _('Продукт')
        verbose_name_plural = _('Продукты')
        ordering = ('sort',)

    category = models.ForeignKey(ProductCategory, null=True, on_delete=models.SET_NULL)
    maker = models.ForeignKey(Producer, null=True, on_delete=models.SET_NULL)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)

    def get_absolute_url(self):
        return '/products/{}/'.format(self.pk)

    @staticmethod
    def get_items():
        return Product.objects.filter(active=True)


class Price(models.Model):
    """Модель цен"""

    class Meta:
        verbose_name = _('Цена')
        verbose_name_plural = _('Цены')

    product = models.ForeignKey(Product, null=True, verbose_name=_('prices'), related_name='prices', on_delete=models.CASCADE)
    value = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return '{}'.format(self.value)

class invoiceManager(models.Manager):

    def get_active(self):
        return self.filter(active=True)


class Invoice(Core):
    """ модель счёта """
    class Meta:
        verbose_name = _('Счет')
        verbose_name_plural = _('Счета')
    users = models.ForeignKey(settings.AUTH_USER_MODEL, null=False, related_name='invoices', on_delete=models.PROTECT)
    objects = invoiceManager()

    @cached_property
    def get_cached_items(self):
        return self.orders.select_related()

    def get_total_sum(self):
        items = self.get_cached_items
        return sum(list(map(lambda x: x.counts * x.ware.prices.all()[0].value, items)))

    def get_total_counts(self):
        items = self.get_cached_items
        return sum(list(map(lambda x: x.counts, items)))

class OrderQuerySet(models.QuerySet):
    def delete(self, *args, **kwargs):
        for object in self:
            object.ware.quantity += object.counts
            object.ware.save()
        super(OrderQuerySet, self).delete(*args, **kwargs)


class orderManager(models.Manager):

    def get_active(self):
        return self.filter(active=True)

    def total_sum(self):
        return self.aggregate(summ=Sum(F('price')*F('counts'), output_field=FloatField()))['summ']

    def get_queryset(self):
        return OrderQuerySet(self.model, using=self._db)


class Order(Core):
    """ модель заказа """
    class Meta:
        verbose_name = _('Заказ')
        verbose_name_plural = _('Заказы')

    ware = models.ForeignKey(Product, null=False, related_name='orders', on_delete=models.PROTECT)
    counts = models.IntegerField()
    invoices = models.ForeignKey(Invoice, null=False, related_name='orders', on_delete=models.PROTECT)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    objects = orderManager()

    def _get_product_cost(self):
        return self.ware.prices.all()[0].value * self.counts

    product_cost = property(_get_product_cost)

    @staticmethod
    def get_item(pk):
        return Order.objects.get(pk=pk)

    def save(self, *args, **kwargs):
        if self.pk:
            self.ware.quantity = F('quantity') - (self.counts - self.__class__.get_item(self.pk).counts)
        else:
            self.ware.quantity = F('quantity') - self.counts

        self.ware.save()
        super(self.__class__, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.ware.quantity = F('quantity') + self.counts
        self.ware.save()
        super(self.__class__, self).delete(*args, **kwargs)

geekshop/accounts/views.py
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetView, PasswordResetDoneView,
                                       PasswordResetConfirmView, PasswordResetCompleteView)
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.forms import UserCreationForm
from accounts.models import User, Avatar
from accounts.forms import ShopUserRegisterForm, ShopUserEditForm, ShopUserProfileEditForm
from django.urls import reverse
from django.shortcuts import render, HttpResponseRedirect

from django.contrib import auth

from django.core.mail import send_mail
from django.conf import settings

from django.db import transaction
from django.contrib.auth.decorators import login_required

from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator


def register(request):
    title = 'регистрация'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            user = register_form.save()
            if send_verify_mail(user):
                print('сообщение для подтверждения регистрации отправлено')
                success_message = _('Сообщение для подтверждения регистрации отправлено')
                messages.success(request, success_message)
                return HttpResponseRedirect(reverse('accounts:login'))
            else:
                print('ошибка отправки сообщения для подтверждения регистрации')
                success_message = _('Ошибка отправки сообщения для подтверждения регистрации')
                messages.success(request, success_message)
                return HttpResponseRedirect(reverse('accounts:login'))
    else:
        register_form = ShopUserRegisterForm()

    content = {'title': title, 'register_form': register_form}

    return render(request, 'accounts/register.html', content)


def send_verify_mail(user):
    verify_link = reverse(
        'accounts:verify',
        args=[user.email, user.activation_key])

    title = 'Подтверждение учетной записи {}'.format(user.username)
    message = 'Для подтверждения учетной записи {0} \
    на портале {1} перейдите по ссылке: \
    \n{1}{2}'.format(user.username, settings.DOMAIN_NAME, verify_link)

    print('from: {}, to: {}'.format(settings.EMAIL_HOST_USER, user.email))
    return send_mail(
            title,
            message,
            settings.EMAIL_HOST_USER,
            [user.email],
            fail_silently=False,
        )


def verify(request, email, activation_key):
    try:
        user = User.objects.get(email=email)
        if user.activation_key == activation_key and not user.is_activation_key_expired():
            print('user {} is activated'.format(user))
            user.is_active = True
            user.save()
            auth.login(request, user)

            return render(request, 'accounts/verification.html')
        else:
            print('error activation user: {}'.format(user))
            return render(request, 'accounts/verification.html')

    except Exception as e:
        print('error activation user : {}'.format(e.args))

    return HttpResponseRedirect(reverse('basket:mainView'))

@login_required
@transaction.atomic
def edit(request):
    title = 'редактирование'

    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        profile_form = ShopUserProfileEditForm(request.POST, instance=request.user.userprofile)
        if edit_form.is_valid() and profile_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('accounts:profile'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)
        profile_form = ShopUserProfileEditForm(instance=request.user.userprofile)

    content = {'title': title, 'edit_form': edit_form, 'profile_form': profile_form}

    return render(request, 'accounts/user_form.html', content)



class MyPasswordResetView(PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    email_template_name = 'accounts/password_reset_email.html'

class MyPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'

class MyPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'

class MyPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'

class login(SuccessMessageMixin, LoginView):
    """docstring for LoginView"""
    template_name = 'accounts/login.html'
    success_message = _('Вход в систему выполнен')

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(LoginView, self).dispatch(request, *args, **kwargs)

class logout(LogoutView):
    """docstring for logoutView"""
    success_message = _('Вы вышли из системы')
    #template_name = 'registration/logged_out.html'

    def get_next_page(self):
        next_page = super().get_next_page()
        if next_page:
            messages.success(self.request, self.success_message)
        return next_page

class createProfileView(CreateView):
    """docstring for DelView"""
    model = User

class profileView(DetailView):
    """docstring for AddView"""
    model = User

    def get_object(self, queryset=None):
        return self.request.user

class changeProfileView(UpdateView):
    """docstring for AddView"""
    fields = ('username', 'first_name', 'last_name', 'email', 'description')
    form = UserCreationForm
    model = User
    success_url = '/'

    def get_object(self, queryset=None):
        return self.request.user

class deleteProfileView(DeleteView):
    """docstring for DelView"""

    model = User

class createAvatarView(CreateView):
    """docstring for DelView"""
    fields = ('image', 'title')
    model = Avatar

    def form_valid(self, form):
        form.instance.related_obj = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('accounts:profile')

class avatarView(DetailView):
    """docstring for AddView"""
    model = Avatar

class changeAvatarView(UpdateView):
    """docstring for AddView"""
    fields = ('image', 'title')
    form = UserCreationForm
    model = Avatar
    success_url = '/'

class deleteAvatarView(DeleteView):
    """docstring for DelView"""
    model = Avatar

    def get_success_url(self):
        return reverse('accounts:profile')

geekshop/accounts/templates/accounts/avatar_confirm_delete.html
{% extends "basket/base.html" %}
{% load static i18n %}

{% block head %}
    {% include 'basket/includes/head.html' with name='Удалить аватарку' %}
{% endblock head %}

{% block container %}
     <div class="hero">
	    {% include 'basket/includes/header.html' with hello=1 %}
		<h1>{% trans 'Удаление аватарки' %}</h1>
    </div>

    <div class="details-slider">
        <div class="slider-product"><img src="{{object.image.url}}" style="max-width:100%;max-height:100%;"></div>
    </div>
    <div class="description" style="text-align:center">
        <form method="post">
            {% csrf_token %}
            <button type="submit" >{% trans 'Удалить?' %}</button>
        </form>
    </div>
{% endblock container %}

geekshop/accounts/templates/accounts/avatar_form.html
{% extends "basket/base.html" %}
{% load static i18n %}

{% block head %}
    {% include 'basket/includes/head.html' with name='Аватарка' %}
{% endblock head %}

{% block container %}
     <div class="hero">
	    {% include 'basket/includes/header.html' with hello=1 %}
		<h1>{% trans 'Загрузить аватарку' %}</h1>
    </div>
    <div class="center" style="text-align:center;">
        <form method="post" style="text-align:left;margin:auto;display:inline-block;" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="{% trans 'Сохранить' %}">
        </form>
    </div>
{% endblock container %}

geekshop/accounts/templates/accounts/login.html
{% extends "basket/base.html" %}
{% load static i18n %}

{% block head %}
    {% include 'basket/includes/head.html' with name='Вход' %}
{% endblock head %}

{% block container %}
    <div class="hero">
	    {% include 'basket/includes/header.html' with hello=1 %}
        {% include 'basket/includes/snippets/messages.html' %}
		<h1>{% trans 'Вход в профиль' %}</h1>
    </div>
    <div class="center" style="text-align:center;">
        <form action="{% url 'accounts:login' %}" method="post" >
            {% csrf_token %}
            {{form}}
        <input type="submit" name="{% trans 'Войти' %}">
        </form>
        <a href="{% url 'accounts:password_reset' %}">Забыли пароль? Сбросьте его!</a>
        <br>
        <button class="btn btn-round form-control">
            <a href="{% url 'accounts:register' %}" class="">
                Зарегистрироваться
            </a>
        </button>
        <br>
        <button class="btn btn-round form-control">
            <a href="{% url 'social:begin' 'google-oauth2' %}?next=/">
                Google+ sign in
            </a>
        </button>

    </div>

{% endblock container %}

geekshop/accounts/templates/accounts/password_reset_complete.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block extrastyle %}
{% include 'basket/includes/head.html' %}
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Домой' %}</a>
&rsaquo; {% trans 'Сброс пароля' %}
</div>
{% endblock %}

{% block title %}{% trans 'Сброс пароля' %}{% endblock %}
{% block content_title %}<h1>{% trans 'Сброс пароля' %}</h1>{% endblock %}

{% block content %}

<p>{% trans "Ваш новый пароль был установлен.  Используйте его для входа в систему." %}</p>

<p><a href="{% url 'accounts:login' %}">{% trans 'Войти' %}</a></p>

{% endblock %}

geekshop/accounts/templates/accounts/password_reset_confirm.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}
{% include 'basket/includes/head.html' %}
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Домой' %}</a>
&rsaquo; {% trans 'Подтверждение сброса пароля' %}
</div>
{% endblock %}

{% block title %}{% trans 'Подтверждение сброса пароля' %}{% endblock %}
{% block content_title %}<h1>{% trans 'Подтверждение сброса пароля' %}</h1>{% endblock %}
{% block content %}

{% if validlink %}

<p>{% trans "Пожалуйста, введите ваш пароль дважды, чтобы мы могли проверить, что вы его ввели правильно." %}</p>

<form method="post">{% csrf_token %}
<fieldset class="module aligned">
    <div class="form-row field-password1">
        {{ form.new_password1.errors }}
        <label for="id_new_password1">{% trans 'Новый пароль:' %}</label>
        {{ form.new_password1 }}
    </div>
    <div class="form-row field-password2">
        {{ form.new_password2.errors }}
        <label for="id_new_password2">{% trans 'Подтвердите пароль:' %}</label>
        {{ form.new_password2 }}
    </div>
    <input type="submit" value="{% trans 'Изменить мой пароль' %}">
</fieldset>
</form>

{% else %}

<p>{% trans "Ссылка на сброс пароля не валидна, возможно, потому что она уже была использована." %}</p>

{% endif %}

{% endblock %}

geekshop/accounts/templates/accounts/password_reset_done.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block extrastyle %}
{% include 'basket/includes/head.html' %}
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Домой' %}</a>
&rsaquo; {% trans 'Сброс пароля' %}
</div>
{% endblock %}

{% block title %}{% trans 'Сброс пароля' %}{% endblock %}
{% block content_title %}<h1>{% trans 'Сброс пароля' %}</h1>{% endblock %}
{% block content %}

<p>{% trans "Мы сбросили инструкции установки нового пароля на указанный вами адрес электронной почты (конечно, если существует аккаунт с этой почтой)." %}</p>

<p>{% trans "Если вы не получили письмо, то убедитесь, что вы верно указали ваш адрес электронной почты, и проверьте папку спама." %}</p>

{% endblock %}

geekshop/accounts/templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}Вы получили данное письмо потому, что вы запросили сброс пароля для вашего аккаунта на сайте {{ site_name }}.{% endblocktrans %}

{% trans "Пожалуйста, пройдите на следующую страницу и выберите новый пароль:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Ваше имя пользователя:" %} {{ user.get_username }}

{% trans "Спасибо, что используете наш сайт!" %}

{% blocktrans %}Команда сайта {{ site_name }}{% endblocktrans %}

{% endautoescape %}

geekshop/accounts/templates/accounts/password_reset_form.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}
{% include 'basket/includes/head.html' %}
{% endblock %}


{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Домой' %}</a>
&rsaquo; {% trans 'Сброс пароля' %}
</div>
{% endblock %}

{% block title %}{% trans 'Сброс пароля' %}{% endblock %}
{% block content_title %}<h1>{% trans 'Сброс пароля' %}</h1>{% endblock %}
{% block content %}

<p>{% trans "Забыли свой пароль? Введите свой email адрес и мы вышлем инструкции на него для установки нового пароля." %}</p>

<form method="post">{% csrf_token %}
<fieldset class="module aligned">
    <div class="form-row field-email">
        {{ form.email.errors }}
        <label for="id_email">{% trans 'Адрес электронной почты:' %}</label>
        {{ form.email }}
    </div>
    <input type="submit" value="{% trans 'Сбросить мой пароль' %}">
</fieldset>
</form>

{% endblock %}

geekshop/accounts/templates/accounts/register.html
{% extends "basket/base.html" %}
{% load static i18n %}

{% block head %}
    {% include 'basket/includes/head.html' with name='Регистрация' %}
{% endblock head %}

{% block container %}
    <div class="hero">
	    {% include 'basket/includes/header.html' with hello=1 %}
		<h1>{% trans 'Регистрация пользователя' %}</h1>
    </div>
    <div class="center" style="text-align:center;">
        <form action="{% url 'accounts:register' %}" method="post" >
            {% csrf_token %}
            {{ register_form.as_p }}
        <input type="submit" name="{% trans 'Зарегистрироваться' %}">
        </form>
    </div>

{% endblock container %}

geekshop/accounts/templates/accounts/user_detail.html
{% extends "basket/base.html" %}
{% load static i18n %}

{% block head %}
    {% include 'basket/includes/head.html' with name='Профиль' %}
{% endblock head %}

{% block container %}
        <div class="hero">
	        {% include 'basket/includes/header.html' with hello=1 %}
		    <h1>{% trans 'Профиль пользователя' %}</h1>
        </div>

        <div class="details">

                {% if object %}
                        <div class="details-products">
                                <div class="details-slider">
                                        {% with images=object.pictures.all  %}
                                                <div class="slider-product"><img src="{{images.0.image.url}}" style="max-width:100%;max-height:100%;"></div>
                                                {% include 'accounts/includes/snippets/pic_gallery.html' with images=images %}
                                        {% endwith %}
                                </div>

                                <div class="description">
                                        <h3>{{user.first_name|default:user.username}}</h3>
                                        <h3>{{user.second_name|default:''}}</h3>
                                        <p>{{user.email}}</p>
                                        <div class="description-text">
                                                {{user.description|default:''|linebreaks}}
                                        </div>
                                        <a href="{% url 'accounts:edit' %}" class="{{button_order_cls}}">{% trans 'Редактировать' %}</a>
                                </div>
                        </div>
                {% endif %}
        </div>
{% endblock container %}

geekshop/accounts/templates/accounts/user_form.html
{% extends "basket/base.html" %}
{% load static i18n %}

{% block head %}
    {% include 'basket/includes/head.html' with name='Редактировать профиль' %}
{% endblock head %}

{% block container %}
    <div class="hero">
	    {% include 'basket/includes/header.html' with hello=1 %}
		<h1>{% trans 'Редактирование профиля' %}</h1>
    </div>

    <div class="center" style="text-align:center;">
        <form action="{% url 'accounts:edit' %}" method="post" style="text-align:left;margin:auto;display:inline-block;">
            {% csrf_token %}
            {{ edit_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="{% trans 'Сохранить изменения' %}">
        </form>
    </div>
    <div class="details-slider">
        {% include 'accounts/includes/snippets/pic_gallery.html' with images=object.pictures.all %}
    </div>
{% endblock container %}

geekshop/accounts/templates/accounts/verification.html
{% extends "basket/base.html" %}
{% load static i18n %}

{% block head %}
    {% include 'basket/includes/head.html' with name='Верификация' %}
{% endblock head %}

{% block container %}
    <div class="hero">
	    {% include 'basket/includes/header.html' with hello=1 %}
		<h2>{% trans 'Верификация пользователя' %}</h2>
    </div>
    <div class="center" style="text-align:center;">
        {% if user %}
            <h3>Поздравляем!</h3>
            <br>
            <h4>Пользователь {{user.username}} подтвержден.</h4>
        {% else %}
            <h3>Верификация не пройдена.</h3>
        {% endif %}
        <br>
        <button class="btn btn-round form-control">
            <a href="{% url 'basket:mainView' %}" class="">
                на главную
            </a>
    </button>
    </div>

{% endblock container %}