geekshop/accounts/urls.py
from django.urls import re_path
from .views import (login, logout,
    createProfileView, profileView, changeProfileView, deleteProfileView,
    createAvatarView, avatarView, changeAvatarView, deleteAvatarView, MyPasswordResetView, register, verify, edit)

app_name = 'accounts'

urlpatterns = [
    re_path('login/', login.as_view(), name='login'),
    re_path('logout/', logout.as_view(), name='logout'),
    re_path('profile/', profileView.as_view(), name='profile'),
    re_path('edituserprof/', edit, name='edit'),
    re_path('deleteprofile/',  deleteProfileView.as_view(), name='deleteProfile'),
    re_path('createavatar/',  createAvatarView.as_view(), name='createAvatar'),
    re_path('delavatar/(?P<pk>\d+)/',  deleteAvatarView.as_view(), name='deleteAvatar'),
    re_path(r'password_reset', MyPasswordResetView.as_view(), name='password_reset'),
    re_path(r'^register/$', register, name='register'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w*)/$', verify, name='verify'),
]

geekshop/basket/urls.py
from django.urls import re_path
from .views import (MainView, ContView, ProdView, ProdCategoryView,
                    ProdDetailView, AddProductView, DelProductView, UpdateProductView, OrderProductView, BasketView,
                    createPictureView, pictureView, deletePictureView, OrderDeleteProductView, OrderAddProductView,
                    PayInvoiceView, basket_edit, DeleteProductFromOrder)


app_name = 'basket'

urlpatterns = [
    re_path(r'index/', MainView.as_view(), name='mainView'),
    re_path(r'^$', MainView.as_view(), name='mainView'),
    re_path(r'products/page/(?P<page>\d+)/', ProdView.as_view(), name='prodView'),
    re_path(r'contact/', ContView.as_view(), name='contView'),
    re_path(r'products/category/(?P<cat_id>\d+)/page/(?P<page>\d+)/', ProdCategoryView.as_view(), name='prodCategoryView'),
    re_path(r'products/(?P<slug>\d+)/', ProdDetailView.as_view(), name='prodDetailView'),
    re_path(r'^addproduct/(?P<cat_id>\d+)', AddProductView.as_view(), name='addProductView'),
    re_path(r'^delproduct/(?P<pk>\d+)/', DelProductView.as_view(), name='delProductView'),
    re_path(r'edit_basket/(?P<pk>\d+)/(?P<quantity>\d+)/$', basket_edit, name='basket_edit'),
    re_path(r'delete_product_basket/(?P<pk>\d+)/$', DeleteProductFromOrder.as_view(), name='deleteProductFromOrder'),
    re_path(r'updateproduct/(?P<pk>\d+)/', UpdateProductView.as_view(), name='updateProductView'),
    re_path(r'order/(?P<pk>\d+)', OrderProductView.as_view(), name='orderProductView'),
    re_path(r'order/deleteproduct/(?P<pk>\d+)/', OrderDeleteProductView.as_view(), name='orderDeleteProductView'),
    re_path(r'order/addproduct/(?P<pk>\d+)/', OrderAddProductView.as_view(), name='orderAddProductView'),
    re_path(r'^basket/', BasketView.as_view(), name='basketView'),
    re_path(r'createPicture/(?P<related_obj>\d+)/', createPictureView.as_view(), name='createPicture'),
    re_path(r'picture/(?P<pk>\d+)/', pictureView.as_view(), name='pictureView'),
    re_path(r'deletePicture/(?P<pk>\d+)/', deletePictureView.as_view(), name='deletePicture'),
    re_path(r'payinvoice/', PayInvoiceView.as_view(), name='payinvoice')
]

geekshop/geekshop/urls.py
import os
from django.contrib import admin
from django.urls import include, re_path
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import login, MyPasswordResetDoneView, MyPasswordResetConfirmView, MyPasswordResetCompleteView
import basket.views as basket

app_name = 'geekshop'

urlpatterns = [
    re_path(r'^$', basket.MainView.as_view(), name='main'),
    re_path(r'', include('basket.urls', namespace='basket')),
    re_path(r'admin/', admin.site.urls),
    re_path(r'admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r'^ordersapp/', include('ordersapp.urls', namespace='order')),
    re_path(r'^auth/verify/google/oauth2/', include("social_django.urls", namespace="social")),
    re_path(r'auth/', include('accounts.urls', namespace='accounts')),
    re_path(r'^rosetta/', include('rosetta.urls')),
    re_path(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^accounts/password/reset/done/$', MyPasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^reset/confirm/done/$', MyPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    re_path(r'accounts/login/', login.as_view(), name='login'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#if settings.DEBUG:
#    import debug_toolbar
#    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path

app_name = "ordersapp"

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),

    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),

    re_path(r'^product/(?P<pk>\d+)/price/$', ordersapp.get_product_price),
]

geekshop/basket/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import HttpResponseRedirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .models import Product, Contact, ProductCategory, Invoice, Order, Picture
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages

from django.urls import reverse
from django.conf import settings

from django.template.loader import render_to_string
from django.http import JsonResponse

from django.core.cache import cache

from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.db import connection


def get_category(id):
    if settings.LOW_CACHE:
        key = 'category_{}'.format(id)
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, id=id)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, id=id)


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)



class changeTemplateNameMixin(object):

    def get_template_names(self):
        old_template, new_template = settings.TEMPLATE_CHANGE
        template_names = super().get_template_names()
        if old_template != new_template:
            template_names = self.changedNamesList(template_names, old_template, new_template)
        return template_names

    @staticmethod
    def changedNamesList(template_names, old_template, new_template):
        return [name.replace(old_template, new_template) for name in template_names]

class BasketView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'basket/order.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        invoice_qs = Invoice.objects.get_active().filter(users=self.request.user)
        if (invoice_qs.exists()):
            context['orders'] = Order.objects.filter(invoices=invoice_qs[0]).select_related()
        else:
            context['orders'] = []

        return context

class OrderProductView(ListView):
    """ Класс вывода заказа """
    model = Order
    template_name = 'basket/order.html'

    def create_new_order(self, add_invoice):
        new_order = Order()
        new_order.title = "Заказ продукта {}".format(self.kwargs['pk'])
        new_order.ware = get_product(int(self.kwargs['pk']))
        new_order.price = new_order.ware.prices.all()[0].value
        new_order.counts = 1
        new_order.invoices = add_invoice
        new_order.active = True
        new_order.save()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_invoice = ''

        invoice_qs = Invoice.objects.get_active().filter(users=self.request.user)

        if (not invoice_qs.exists()):
            new_invoice = Invoice()
            new_invoice.title = "Счёт пользователя {}".format(self.request.user.id)
            new_invoice.users = self.request.user
            new_invoice.active = True
            new_invoice.save()
            user_invoice = new_invoice
        else:
            user_invoice = invoice_qs[0]

        order_qs = Order.objects.filter(invoices=user_invoice)

        if (not order_qs.exists()):
            self.create_new_order(user_invoice)
        else:
            is_product_added = False
            for order_entry in order_qs:
                if order_entry.ware.id == int(self.kwargs['pk']):
                    order_entry.counts += 1
                    order_entry.save()
                    is_product_added = True
            if (not is_product_added):
                self.create_new_order(user_invoice)

        context['orders'] = Order.objects.filter(invoices=user_invoice)

        return context

    def render_to_response(self, context, **response_kwargs):
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))


class DeleteProductFromOrder(ListView):
    model = Order
    template_name = "basket/order.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_invoice = Invoice.objects.get_active().filter(users=self.request.user)[0]

        order_item = Order.objects.get(pk=int(self.kwargs['pk']))
        order_item.delete()
        order_qs = Order.objects.filter(invoices=user_invoice)
        if not order_qs.exists():
            user_invoice.delete()

        invoice_qs = Invoice.objects.get_active().filter(users=self.request.user)
        if invoice_qs.exists():
            context['orders'] = Order.objects.filter(invoices=invoice_qs[0])

        return context

    def render_to_response(self, context, **response_kwargs):
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))



class OrderDeleteProductView(ListView):
    model = Order
    template_name = "basket/order.html"
    success_message = _('Количество товаров было уменьшено до %s')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_invoice = Invoice.objects.get_active().filter(users=self.request.user)[0]

        order_qs = Order.objects.filter(invoices=user_invoice)
        order_product = ''
        for order_entry in order_qs:
            if order_entry.ware.id == int(self.kwargs['pk']):
                order_product = order_entry

        order_product.counts -= 1
        if order_product.counts == 0:
            order_product.delete()
            self.success_message = ""
            order_qs = Order.objects.filter(invoices=user_invoice)
            if not order_qs.exists():
                user_invoice.delete()
        else:
            order_product.save()
            self.success_message = self.success_message % order_product.counts

        invoice_qs = Invoice.objects.get_active().filter(users=self.request.user)
        if invoice_qs.exists():
            context['orders'] = Order.objects.filter(invoices=invoice_qs[0])

        messages.success(self.request, self.success_message)
        return context

class OrderAddProductView(ListView):
    model = Order
    template_name = "basket/order.html"
    success_message = _('Количество товаров было увеличено до %s')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_invoice = Invoice.objects.get_active().filter(users=self.request.user)[0]

        order_qs = Order.objects.filter(invoices=user_invoice)
        for order_entry in order_qs:
            if order_entry.ware.id == int(self.kwargs['pk']):
                order_entry.counts += 1
                order_entry.save()
                self.success_message = self.success_message % order_entry.counts

        context['orders'] = Order.objects.filter(invoices=user_invoice)

        messages.success(self.request, self.success_message)
        return context

class PayInvoiceView(ListView):
    model = Invoice
    template_name = "basket/order.html"
    success_message = _('Оплата прошла успешно')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        invoice_qs = Invoice.objects.get_active().filter(users=self.request.user)
        if (not invoice_qs.exists()):
            self.success_message = _('Нечего оплачивать')
        else:
            user_invoice = invoice_qs[0]
            user_invoice.active = False
            user_invoice.save()

        messages.success(self.request, self.success_message)
        return context

class MainView(changeTemplateNameMixin, ListView):
    """ Класс вывода index.html """
    model = Product
    template_name = "basket/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = Product.objects.order_by('?')
        return context

class ContView(changeTemplateNameMixin, ListView):
    """ Класс вывода contact_list.html """
    model = Contact

class ProdView(changeTemplateNameMixin, ListView):
    """ Класс вывода product_list.html """
    model = Product
    paginate_by = 2

    def get_context_data(self, **kwargs):
        self.object_list = self.object_list.prefetch_related('pictures')
        context = super().get_context_data(**kwargs)
        context['category'] = ProductCategory.objects.all()
        return context

class ProdCategoryView(changeTemplateNameMixin, ListView):
    """ Класс для отображения товаров по категории """
    model = Product
    paginate_by = 1

    def get_queryset(self):
        self.category = get_category(int(self.kwargs['cat_id']))
        return Product.objects.filter(category=self.category)

    def get_context_data(self, **kwargs):
        self.object_list = self.object_list.prefetch_related('pictures')
        context = super().get_context_data(**kwargs)
        context['cat_id'] = self.category.id
        context['category'] = ProductCategory.objects.all()
        return context

class ProdDetailView(changeTemplateNameMixin, DetailView):
    """ Класс для вывода детальной информации по продукту """
    model = Product
    slug_field = 'pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = ProductCategory.objects.all()
        context['cat_id'] = self.object.category.id
        return context

class AddProductView(CreateView):
    model = Product
    fields = '__all__'

    def get_form_kwargs(self):
        form_kwargs = super().get_form_kwargs()
        cat_id = int(self.kwargs.get('cat_id'))
        if not cat_id == 0:
            form_kwargs['initial'] = {}
            form_kwargs['initial']['category'] = cat_id

geekshop/basket/templates/basket/includes/controll.html
{% load static %}
						<div class="block">
							<a href="#"><img class="control-img" src="{{controll_ref}}" alt="">
								<div class="text"></div>
							</a>
						</div>

geekshop/basket/templates/basket/includes/footer.html
{% load i18n %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>{% trans 'контакты' %}</h3>
            </div>
            <div class="text-footer">
                <a href="/additional/about/"><h3 class="active">{% trans 'полезная информация' %}</h3></a>
            </div>
            <div class="text-footer clearfix">
                <h3>{% trans 'Оставайтесь на связи' %}</h3>
                <p>{% trans 'Подписаться на новости и рассылки' %}</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small"><a href="/additional/rules">{% trans 'Положения &amp; Условия' %}  /  {% trans 'Конфиденциальность' %} &amp; Cookies</a></p>
    </div>

geekshop/basket/templates/basket/includes/head.html
{% load static i18n %}
<head>
	<meta charset="utf-8">
	<title>{% trans name %}</title>
	<link href="{% static 'basket/img/favicon.ico' %}" rel="icon" type="image/x-icon" />
	<link rel="stylesheet" type="text/css" href="{% static 'basket/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'basket/css/style.css' %}">
	<link rel="stylesheet" href="{% static 'basket/fonts/font-awesome/css/font-awesome.css' %}">
	{% block js %}
		<script src="{% static 'basket/js/jquery-3.2.1.min.js' %}"></script>
		<script src="{% static 'basket/js/bootstrap.min.js' %}"></script>
		<script src="{% static 'basket/js/basket_scripts.js' %}"></script>
    {% endblock %}
</head>

geekshop/basket/templates/basket/includes/header.html
{% load i18n %}
<div class="header clearfix">
				<a href="{% url 'basket:mainView' %}" class="logo"></a>
				<ul class="menu">
					{% if user.is_authenticated %}
						<li>
			            	<div class="dropdown">
                				<a class="dropdown-toggle" href="" data-toggle="dropdown">
                    				{{user.first_name|default:user.username}}
                    				<span class="caret"></span>
                				</a>
                				<ul class="dropdown-menu">
                    				<li>
                        				<a href="{% url 'accounts:profile' %}">
                            				профиль
                        				</a>
                    				</li>
                    				<li>
										<a href="{% url 'ordersapp:orders_list' %}">
                            				заказы
                        				</a>
                    				</li>
                				</ul>
            				</div>
        				</li>
					{% endif %}
					<li><a href="{% url 'basket:mainView' %}" {%if home %}class="active"{% endif %}>{% trans 'домой' %}</a></li>
					<li><a href="{% url 'basket:prodView' 1 %}" {%if prod %}class="active"{% endif %}>{% trans 'продукты' %}</a></li>
					<li><a href="{% url 'basket:contView' %}" {%if cont %}class="active"{% endif %}>{% trans 'контакты' %}</a></li>
					{%if not user.is_authenticated %}<li><a href="{% url 'accounts:login' %}">{% trans 'Log in' %}</a></li>{% endif %}
					{%if user.is_authenticated %}<li><a href="{% url 'accounts:logout' %}">{% trans 'Log out' %}</a></li>{% endif %}
					{%if user.is_superuser %}<li><a href="{% url 'admin:index' %}">{% trans 'admin panel' %}</a></li>{% endif %}
				</ul>
				<a href="#" class="search"></a>
				{%if user.is_authenticated %}
					<a href="{% url 'basket:basketView' %}" class="basket">
						<span>
        					{% if invoice %}
            					{{ invoice.get_total_sum|floatformat:0 }} руб
        					{% endif %}
    					</span>
					</a>
				{% endif %}
</div>

geekshop/basket/templates/basket/includes/high_quality_chair.html
{% load static i18n %}
                        <div class="block">
                            <a href="{% url 'basket:prodDetailView' product.id %}"><img {%if home %}class="tab-content-img"{% endif %} src="{{product.pictures.all.0.image.url}}" alt="">
                                <div class="text">
                                    <img src="{% static 'basket/img/icon-hover.png' %}" alt="img">
                                    <h4>{{product.title}}</h4>
                                    <p>{{product.description}} </p>
                                </div>
                            </a>
                        </div>

geekshop/basket/templates/basket/includes/inc_order_list.html
{% load static i18n invoice_tags %}

        {% if invoice %}
            <div class="basket_container">
            <div class="basket_list">
                <p>{% trans 'Счёт' %}: {{invoice.title}}</p>
                    {% for order in orders %}
                    <div class="basket_record">
                        <img src="{{ order.ware.pictures.all.0.image.url }}" alt="{% get_product_description order %}">
                        <span class="category_name">{{ order.ware.category.title }}</span>
                        <span class="product_name">{{ order.ware.title }}</span>
                        <span class="product_price">{{ order.ware.prices.all.0.value }}&nbspруб x</span>
                        <input type="number" name="{{ order.pk }}" min="0" value="{{ order.counts }}">
                        <span class="product_cost">шт. = {{ order.product_cost }}&nbspруб</span>
                        <button class="btn btn-round">
                            <a href="{% url 'basket:deleteProductFromOrder' order.pk %}" class="">
                                удалить
                            </a>
                        </button>
                    </div>
                    {% endfor %}
                <p>{% trans 'СТОИМОСТЬ ЗАКАЗА' %}: {{invoice.get_total_sum}}</p>
                <p>{% trans 'КОЛИЧЕСТВО ВЕЩЕЙ' %}: {{invoice.get_total_counts}}</p>
                <p><a href="{% url 'ordersapp:order_create' %}">Создать заказ</a></p>
            </div>
            </div>
        {% else %}
            <p>{% trans 'Ваша корзина пуста' %}</p>
        {% endif %}

geekshop/basket/templates/basket/includes/links_menu.html
{% load static i18n %}

<div class="links clearfix">
    <ul class="links-menu">
        <li><a href="{% url 'basket:prodView' 1 %}" {% if cat_id == None %}class="active"{% endif %}>все</a></li>
        {% for cat in category %}
            <li><a href="{% url 'basket:prodCategoryView' cat.id 1 %}" {% if cat_id == cat.id %}class="active"{% endif %}>{% trans cat.title %}</a></li>
        {% endfor %}
    </ul>
</div>

geekshop/basket/templates/basket/includes/location.html
{% load i18n %}
<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>{% trans 'Москва' %}</h4>
				<div class="contacts">
					<h5>{% trans 'Телефон' %}</h5>
					<p>{{contact.telephone}}</p>
				</div>
				<div class="contacts">
					<h5>{% trans 'Email' %}</h5>
					<p>{{contact.email}}</p>
				</div>
				<div class="contacts">
					<h5>{% trans 'Адрес' %}</h5>
					<p>{{contact.address}}</p>
				</div>
			</div>

geekshop/basket/templates/basket/includes/product_info.html
{% load static i18n %}

				<div class="details-slider">
					<div class="slider-product">
						<img class="slider-product-img" src="{{product.pictures.all.0.image.url}}">
					</div>
					<div class="slider-control">
						{% include 'basket/includes/controll.html' with controll_ref=product.pictures.all.0.image.url %}
						{% include 'basket/includes/controll.html' with controll_ref=product.pictures.all.0.image.url %}
						{% include 'basket/includes/controll.html' with controll_ref=product.pictures.all.0.image.url %}
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">{% trans product.title %}</h3>
					<h3 class="red">{% trans 'горячее предложение' %}</h3>
					<p class="price"> {{product.prices.all.0.value}} <span>{% trans 'руб' %}</span></p>
					<a href="{% url 'basket:orderProductView' product.id %}" class="red-button">
						{%trans 'заказать' %} <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						<p>{% trans product.description %}</p>
						<p>{% trans 'Отличное качество материалов позволит вам это.' %}</p>
						<p>{% trans 'Различные цвета' %}</p>
						<p>{% trans 'высочайший уровень эргономики и прочность.' %}</p>
					</div>
			    	{%if product %}
    	        		{%if user.is_superuser or user.is_staff %}<a href="{% url 'basket:updateProductView' product.id %}">{% trans 'Изменить' %}</a>{% endif %}
        			{% endif %}
					<p></p>
					{%if product %}
            			{%if user.is_superuser or user.is_staff %}<a href="{% url 'basket:delProductView' product.id %}">{% trans 'Удалить' %}</a>{% endif %}
        			{% endif %}
				</div>