geekshop/basket/urls.py
from django.urls import re_path
from .views import (MainView, ContView, ProdView, ProdCategoryView,
                    ProdDetailView, AddProductView, DelProductView, UpdateProductView, OrderProductView, BasketView,
                    createPictureView, pictureView, deletePictureView, OrderDeleteProductView, OrderAddProductView,
                    PayInvoiceView, basket_edit, DeleteProductFromOrder)


app_name = 'basket'

urlpatterns = [
    re_path(r'index/', MainView.as_view(), name='mainView'),
    re_path(r'^$', MainView.as_view(), name='mainView'),
    re_path(r'products/page/(?P<page>\d+)/', ProdView.as_view(), name='prodView'),
    re_path(r'contact/', ContView.as_view(), name='contView'),
    re_path(r'products/category/(?P<cat_id>\d+)/page/(?P<page>\d+)/', ProdCategoryView.as_view(), name='prodCategoryView'),
    re_path(r'products/(?P<slug>\d+)/', ProdDetailView.as_view(), name='prodDetailView'),
    re_path(r'^addproduct/(?P<cat_id>\d+)', AddProductView.as_view(), name='addProductView'),
    re_path(r'^delproduct/(?P<pk>\d+)/', DelProductView.as_view(), name='delProductView'),
    re_path(r'edit_basket/(?P<pk>\d+)/(?P<quantity>\d+)/$', basket_edit, name='basket_edit'),
    re_path(r'delete_product_basket/(?P<pk>\d+)/$', DeleteProductFromOrder.as_view(), name='deleteProductFromOrder'),
    re_path(r'updateproduct/(?P<pk>\d+)/', UpdateProductView.as_view(), name='updateProductView'),
    re_path(r'order/(?P<pk>\d+)', OrderProductView.as_view(), name='orderProductView'),
    re_path(r'order/deleteproduct/(?P<pk>\d+)/', OrderDeleteProductView.as_view(), name='orderDeleteProductView'),
    re_path(r'order/addproduct/(?P<pk>\d+)/', OrderAddProductView.as_view(), name='orderAddProductView'),
    re_path(r'^basket/', BasketView.as_view(), name='basketView'),
    re_path(r'createPicture/(?P<related_obj>\d+)/', createPictureView.as_view(), name='createPicture'),
    re_path(r'picture/(?P<pk>\d+)/', pictureView.as_view(), name='pictureView'),
    re_path(r'deletePicture/(?P<pk>\d+)/', deletePictureView.as_view(), name='deletePicture'),
    re_path(r'payinvoice/', PayInvoiceView.as_view(), name='payinvoice')
]

geekshop/geekshop/urls.py
import os
from django.contrib import admin
from django.urls import include, re_path
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import login, MyPasswordResetDoneView, MyPasswordResetConfirmView, MyPasswordResetCompleteView
import basket.views as basket

app_name = 'geekshop'

urlpatterns = [
    re_path(r'^$', basket.MainView.as_view(), name='main'),
    re_path(r'', include('basket.urls', namespace='basket')),
    re_path(r'admin/', admin.site.urls),
    re_path(r'admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r'^ordersapp/', include('ordersapp.urls', namespace='order')),
    re_path(r'^auth/verify/google/oauth2/', include("social_django.urls", namespace="social")),
    re_path(r'auth/', include('accounts.urls', namespace='accounts')),
    re_path(r'^rosetta/', include('rosetta.urls')),
    re_path(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^accounts/password/reset/done/$', MyPasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^reset/confirm/done/$', MyPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    re_path(r'accounts/login/', login.as_view(), name='login'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#if settings.DEBUG:
#    import debug_toolbar
#    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/basket/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import HttpResponseRedirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .models import Product, Contact, ProductCategory, Invoice, Order, Picture
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages

from django.urls import reverse
from django.conf import settings

from django.template.loader import render_to_string
from django.http import JsonResponse

from django.core.cache import cache

from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.db import connection


def get_category(id):
    if settings.LOW_CACHE:
        key = 'category_{}'.format(id)
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, id=id)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, id=id)


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)



class changeTemplateNameMixin(object):

    def get_template_names(self):
        old_template, new_template = settings.TEMPLATE_CHANGE
        template_names = super().get_template_names()
        if old_template != new_template:
            template_names = self.changedNamesList(template_names, old_template, new_template)
        return template_names

    @staticmethod
    def changedNamesList(template_names, old_template, new_template):
        return [name.replace(old_template, new_template) for name in template_names]

class BasketView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'basket/order.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        invoice_qs = Invoice.objects.get_active().filter(users=self.request.user)
        if (invoice_qs.exists()):
            context['orders'] = Order.objects.filter(invoices=invoice_qs[0]).select_related()
        else:
            context['orders'] = []

        return context

class OrderProductView(ListView):
    """ Класс вывода заказа """
    model = Order
    template_name = 'basket/order.html'

    def create_new_order(self, add_invoice):
        new_order = Order()
        new_order.title = "Заказ продукта {}".format(self.kwargs['pk'])
        new_order.ware = get_product(int(self.kwargs['pk']))
        new_order.price = new_order.ware.prices.all()[0].value
        new_order.counts = 1
        new_order.invoices = add_invoice
        new_order.active = True
        new_order.save()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_invoice = ''

        invoice_qs = Invoice.objects.get_active().filter(users=self.request.user)

        if (not invoice_qs.exists()):
            new_invoice = Invoice()
            new_invoice.title = "Счёт пользователя {}".format(self.request.user.id)
            new_invoice.users = self.request.user
            new_invoice.active = True
            new_invoice.save()
            user_invoice = new_invoice
        else:
            user_invoice = invoice_qs[0]

        order_qs = Order.objects.filter(invoices=user_invoice)

        if (not order_qs.exists()):
            self.create_new_order(user_invoice)
        else:
            is_product_added = False
            for order_entry in order_qs:
                if order_entry.ware.id == int(self.kwargs['pk']):
                    order_entry.counts += 1
                    order_entry.save()
                    is_product_added = True
            if (not is_product_added):
                self.create_new_order(user_invoice)

        context['orders'] = Order.objects.filter(invoices=user_invoice)

        return context

    def render_to_response(self, context, **response_kwargs):
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))


class DeleteProductFromOrder(ListView):
    model = Order
    template_name = "basket/order.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_invoice = Invoice.objects.get_active().filter(users=self.request.user)[0]

        order_item = Order.objects.get(pk=int(self.kwargs['pk']))
        order_item.delete()
        order_qs = Order.objects.filter(invoices=user_invoice)
        if not order_qs.exists():
            user_invoice.delete()

        invoice_qs = Invoice.objects.get_active().filter(users=self.request.user)
        if invoice_qs.exists():
            context['orders'] = Order.objects.filter(invoices=invoice_qs[0])

        return context

    def render_to_response(self, context, **response_kwargs):
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))



class OrderDeleteProductView(ListView):
    model = Order
    template_name = "basket/order.html"
    success_message = _('Количество товаров было уменьшено до %s')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_invoice = Invoice.objects.get_active().filter(users=self.request.user)[0]

        order_qs = Order.objects.filter(invoices=user_invoice)
        order_product = ''
        for order_entry in order_qs:
            if order_entry.ware.id == int(self.kwargs['pk']):
                order_product = order_entry

        order_product.counts -= 1
        if order_product.counts == 0:
            order_product.delete()
            self.success_message = ""
            order_qs = Order.objects.filter(invoices=user_invoice)
            if not order_qs.exists():
                user_invoice.delete()
        else:
            order_product.save()
            self.success_message = self.success_message % order_product.counts

        invoice_qs = Invoice.objects.get_active().filter(users=self.request.user)
        if invoice_qs.exists():
            context['orders'] = Order.objects.filter(invoices=invoice_qs[0])

        messages.success(self.request, self.success_message)
        return context

class OrderAddProductView(ListView):
    model = Order
    template_name = "basket/order.html"
    success_message = _('Количество товаров было увеличено до %s')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_invoice = Invoice.objects.get_active().filter(users=self.request.user)[0]

        order_qs = Order.objects.filter(invoices=user_invoice)
        for order_entry in order_qs:
            if order_entry.ware.id == int(self.kwargs['pk']):
                order_entry.counts += 1
                order_entry.save()
                self.success_message = self.success_message % order_entry.counts

        context['orders'] = Order.objects.filter(invoices=user_invoice)

        messages.success(self.request, self.success_message)
        return context

class PayInvoiceView(ListView):
    model = Invoice
    template_name = "basket/order.html"
    success_message = _('Оплата прошла успешно')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        invoice_qs = Invoice.objects.get_active().filter(users=self.request.user)
        if (not invoice_qs.exists()):
            self.success_message = _('Нечего оплачивать')
        else:
            user_invoice = invoice_qs[0]
            user_invoice.active = False
            user_invoice.save()

        messages.success(self.request, self.success_message)
        return context

class MainView(changeTemplateNameMixin, ListView):
    """ Класс вывода index.html """
    model = Product
    template_name = "basket/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = Product.objects.order_by('?')
        return context

class ContView(changeTemplateNameMixin, ListView):
    """ Класс вывода contact_list.html """
    model = Contact

class ProdView(changeTemplateNameMixin, ListView):
    """ Класс вывода product_list.html """
    model = Product
    paginate_by = 2

    def get_context_data(self, **kwargs):
        self.object_list = self.object_list.prefetch_related('pictures')
        context = super().get_context_data(**kwargs)
        context['category'] = ProductCategory.objects.all()
        return context

class ProdCategoryView(changeTemplateNameMixin, ListView):
    """ Класс для отображения товаров по категории """
    model = Product
    paginate_by = 1

    def get_queryset(self):
        self.category = get_category(int(self.kwargs['cat_id']))
        return Product.objects.filter(category=self.category)

    def get_context_data(self, **kwargs):
        self.object_list = self.object_list.prefetch_related('pictures')
        context = super().get_context_data(**kwargs)
        context['cat_id'] = self.category.id
        context['category'] = ProductCategory.objects.all()
        return context

class ProdDetailView(changeTemplateNameMixin, DetailView):
    """ Класс для вывода детальной информации по продукту """
    model = Product
    slug_field = 'pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = ProductCategory.objects.all()
        context['cat_id'] = self.object.category.id
        return context

class AddProductView(CreateView):
    model = Product
    fields = '__all__'

    def get_form_kwargs(self):
        form_kwargs = super().get_form_kwargs()
        cat_id = int(self.kwargs.get('cat_id'))
        if not cat_id == 0:
            form_kwargs['initial'] = {}
            form_kwargs['initial']['category'] = cat_id

geekshop/basket/templates/basket/base.html
<!DOCTYPE html>
{% load static i18n %}
<html>
{% block head %}
    {% include 'basket/includes/head.html' with name='Магазин' %}
{% endblock head %}
<body>
	<div class="container">
        {% block container %}
		<div class="slider">
			{% include 'basket/includes/header.html' with home=1 %}
			{% include './includes/snippets/messages.html' %}
			<div class="text-slider">
				<h3 class="green">{% trans 'тенденции' %}</h3>
				<h3 class="big"> {% trans 'удобные стулья' %}</h3>
				<p>{% trans 'Новый уровень комфорта. Отличные характеристики.' %}</p>
				<a href="#" class="button-order">{% trans 'заказать' %} <img src="{% static 'basket/img/arrow.png' %}" alt=""></a>
			</div>
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>

		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">{% trans 'Популярные' %}</a><a href="#">{% trans 'Новинки' %}</a>
			</div>
			<a class="explore" href="#">{% trans 'показать все' %} <img src="{% static 'basket/img/arrow.png' %}" alt=""></a>
			<div class="clearfix">
			</div>
            {% block tab_content %}{% endblock tab_content %}
		</div>

        {% endblock container %}

		<div class="clr"></div>

	</div>

	{% include 'basket/includes/footer.html' %}

</body>
</html>

geekshop/basket/templates/basket/contact_list.html
{% extends "basket/base.html" %}
{% load static i18n %}

{% block head %}
    {% include 'basket/includes/head.html' with name='Контакты' %}
{% endblock head %}

{% block container %}
		<div class="hero">
			{% include 'basket/includes/header.html' with cont=1 %}
			<h1>{% trans 'наши контакты' %}</h1>
		</div>

		<div class="location">
			{% for contact in object_list %}
				{% include 'basket/includes/location.html' %}
			{% endfor %}
		</div>
{% endblock container %}

geekshop/basket/templates/basket/index.html
{% extends "basket/base.html" %}

{% block head %}
    {% include 'basket/includes/head.html' with name='Магазин' %}
{% endblock head %}

{% block tab_content %}
			<div class="tab-content">
				{% include 'basket/includes/high_quality_chair.html' with product=object_list.0 home=1 %}
				{% include 'basket/includes/high_quality_chair.html' with product=object_list.1 home=1 %}
			</div>
{% endblock tab_content %}

geekshop/basket/templates/basket/order.html
<!DOCTYPE html>
{% load static i18n invoice_tags %}
<html>
{% include 'basket/includes/head.html' with name='Заказы' %}
<body>
	<div class="container">

		<div class="hero">
			{% include 'basket/includes/header.html' %}
            {% include './includes/snippets/messages.html' %}
			<h1>{% trans 'ваши заказы' %}</h1>
		</div>

        {% include 'basket/includes/inc_order_list.html' %}

		<div class="clr"></div>
	</div>

	{% include 'basket/includes/footer.html' %}

</body>
</html>

geekshop/basket/templates/basket/picture_confirm_delete.html
{% extends "basket/base.html" %}
{% load static i18n %}

{% block head %}
    {% include 'basket/includes/head.html' with name='Удалить картинку' %}
{% endblock head %}

{% block container %}
     <div class="hero">
	    {% include 'basket/includes/header.html' %}
		<h1>{% trans 'Удаление картинки' %}</h1>
    </div>

    <div class="details-slider">
        <div class="slider-product"><img src="{{object.image.url}}" style="max-width:100%;max-height:100%;"></div>
    </div>
    <div class="description" style="text-align:center">
        <form method="post">
            {% csrf_token %}
            <button type="submit" >{% trans 'Удалить?' %}</button>
        </form>
    </div>
{% endblock container %}

geekshop/basket/templates/basket/picture_form.html
{% extends "basket/base.html" %}
{% load static i18n %}

{% block head %}
    {% include 'basket/includes/head.html' with name='Картинка' %}
{% endblock head %}

{% block container %}
     <div class="hero">
	    {% include 'basket/includes/header.html' %}
		<h1>{% trans 'Загрузить картинку' %}</h1>
    </div>
    <div class="center" style="text-align:center;">
        <form method="post" style="text-align:left;margin:auto;display:inline-block;" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="{% trans 'Сохранить' %}">
        </form>
    </div>
{% endblock container %}

geekshop/basket/templates/basket/product_confirm_delete.html
{% extends "basket/base.html" %}
{% load static i18n %}

{% block head %}
    {% include 'basket/includes/head.html' with name='Удалить продукт' %}
{% endblock head %}

{% block container %}
        <form method="post">
            {% csrf_token %}
            <p>{% trans 'Вы уверены, что хотите удалить' %} "{{ object }}"?</p>
            <input type="submit" value="{% trans 'Удалить' %}">
        </form>
{% endblock container %}

geekshop/basket/templates/basket/product_detail.html
<!DOCTYPE html>
{% load static i18n %}
<html>
{% include 'basket/includes/head.html' with name='Каталог' %}
<body>
	<div class="container">
		<div class="hero-white">
			{% include 'basket/includes/header.html' with prod=1 %}
		</div>

		<div class="details">
			{% include 'basket/includes/links_menu.html' with product=object %}
			{% include 'basket/includes/product_info.html' with product=object %}
		</div>

		<div class="clr"></div>

	</div>

	{% include 'basket/includes/footer.html' %}

</body>
</html>

geekshop/basket/templates/basket/product_form.html
{% extends "basket/base.html" %}
{% load static i18n %}

{% block head %}
    {% include 'basket/includes/head.html' %}
{% endblock head %}

{% block container %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="{% trans 'Сохранить' %}">
        </form>

        {%if object %}
            <div class="details-slider">
                {% include 'basket/includes/snippets/pic_gallery.html' with images=object.pictures.all %}
            </div>
        {% endif %}
{% endblock container %}

geekshop/basket/templates/basket/product_list.html
{% extends "basket/base.html" %}
{% load static i18n %}

{% block head %}
    {% include 'basket/includes/head.html' with name='Каталог' %}
{% endblock head %}

{% block container %}
		<div class="hero-white">
			{% include 'basket/includes/header.html' with prod=1 %}
		</div>

		<div class="details">
			{% include 'basket/includes/links_menu.html' %}
			{% include 'basket/includes/product_info.html' with product=object_list.0 %}

			<div class="related">
				<div class="title clearfix">
					<h2>{% trans 'Похожие продукты' %}</h2>
					<a class="explore" href="#">{% trans 'показать все' %} <img src="{% static 'basket/img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">
					{%if user.is_superuser or user.is_staff %}
						<div class="block">
							<a href="{% url 'basket:addProductView' cat_id|default:0 %}">{% trans 'Добавить' %}</a>
						</div>
					{% endif %}
					{% for product in object_list %}
						{% include 'basket/includes/high_quality_chair.html' %}
					{% endfor %}
				</div>

				<div class="paginator">
          			{% if page_obj.has_previous %}
						{% if cat_id %}
            				<a href="{% url 'basket:prodCategoryView' cat_id page_obj.previous_page_number %}"><</a>
						{% else %}
            				<a href="{% url 'basket:prodView' page_obj.previous_page_number %}"><</a>
						{% endif %}
          			{% endif %}
          			<span class="current">
            			страница {{ page_obj.number }} из
            			{{ page_obj.paginator.num_pages }}
          			</span>
          			{% if page_obj.has_next %}
						{% if cat_id %}
            				<a href="{% url 'basket:prodCategoryView' cat_id page_obj.next_page_number %}">></a>
						{% else %}
            				<a href="{% url 'basket:prodView' page_obj.next_page_number %}">></a>
						{% endif %}
          			{% endif %}
        </div>
      </div>

			</div>
		</div>
{% endblock container %}